<#
.SYNOPSIS
    SDT Installer - sets up the 'sdt' command on this user's PATH.

.DESCRIPTION
    Downloads the latest SDT release from GitHub, extracts to
    %LOCALAPPDATA%\Magna5\SDT, adds a shim to the user PATH, and creates
    a Start Menu shortcut.

    After install, open any new PowerShell or cmd window and type 'sdt'
    to launch the browser GUI. 'sdt cli' runs the console version. The
    script self-updates on every launch, so this installer only needs to
    run once per box.

.NOTES
    Run as the logged-in user (no admin required).
    Paste the one-liner:
        iwr https://raw.githubusercontent.com/matt-magna5/SDT/main/install.ps1 -UseBasicParsing | iex
#>
[CmdletBinding()]
param(
    [string] $Version = 'latest',   # 'latest' or a tag like 'v3.11'
    [switch] $Quiet,
    [switch] $NoShortcut
)

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

# ----- TLS 1.2 for GitHub on older hosts -------------------------------------
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}

function Say { param([string]$m, [string]$c='White') if (-not $Quiet) { Write-Host "  $m" -ForegroundColor $c } }

Say ""
Say "================================================================" DarkMagenta
Say "  MAGNA5 SDT Installer" Magenta
Say "================================================================" DarkMagenta
Say ""

# ----- Paths -----------------------------------------------------------------
$Root     = Join-Path $env:LOCALAPPDATA 'Magna5\SDT'
$BinDir   = Join-Path $Root 'bin'
$AppDir   = Join-Path $Root 'app'
$ZipFile  = Join-Path $Root 'sdt.zip'
$ShimPS   = Join-Path $BinDir 'sdt.ps1'
$ShimCmd  = Join-Path $BinDir 'sdt.cmd'

foreach ($d in @($Root, $BinDir, $AppDir)) {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
}

# ----- Resolve latest version if requested -----------------------------------
if ($Version -eq 'latest') {
    Say "Checking GitHub for latest release..." DarkCyan
    try {
        $rel = Invoke-WebRequest -Uri 'https://api.github.com/repos/matt-magna5/SDT/releases/latest' -UseBasicParsing -TimeoutSec 10
        $Version = ($rel.Content | ConvertFrom-Json).tag_name
    } catch {
        Say "Releases API failed: $($_.Exception.Message)" Yellow
        # Probe fallback
        for ($minor = 11; $minor -ge 0; $minor--) {
            $try = "v3.$minor"
            try {
                $h = Invoke-WebRequest -Uri "https://github.com/matt-magna5/SDT/archive/refs/tags/$try.zip" -Method Head -UseBasicParsing -TimeoutSec 5
                if ($h.StatusCode -eq 200) { $Version = $try; break }
            } catch { continue }
        }
        if (-not $Version -or $Version -eq 'latest') { throw "Could not determine latest SDT version" }
    }
    Say "Latest: $Version" DarkGreen
}
$VerClean = $Version -replace '^v',''

# ----- Download --------------------------------------------------------------
$url = "https://github.com/matt-magna5/SDT/archive/refs/tags/$Version.zip"
Say "Downloading $Version ..." DarkCyan
Say "  $url" DarkGray
Invoke-WebRequest -Uri $url -OutFile $ZipFile -UseBasicParsing -TimeoutSec 120

# ----- Extract (replace AppDir contents atomically-ish) ----------------------
$stage = Join-Path $Root ("stage-" + [guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Force -Path $stage | Out-Null
Expand-Archive -Path $ZipFile -DestinationPath $stage -Force
$extracted = Get-ChildItem $stage -Directory | Select-Object -First 1
if (-not $extracted) { throw "Extraction produced no folder" }

# Wipe AppDir, copy fresh
Get-ChildItem $AppDir -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Copy-Item -Path (Join-Path $extracted.FullName '*') -Destination $AppDir -Recurse -Force
Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item $ZipFile -Force -ErrorAction SilentlyContinue
Say "Installed to $AppDir" DarkGreen

# ----- Write shim scripts ----------------------------------------------------
# sdt.ps1 - dispatches to GUI (default) or CLI (on 'cli' arg)
@"
# SDT launcher shim - auto-generated by install.ps1
param([Parameter(Position=0)][string]`$Mode = 'gui', [Parameter(ValueFromRemainingArguments=`$true)]`$Rest)
`$AppDir = '$AppDir'
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
if (`$Mode -match '^(cli|console|tui)$') {
    & (Join-Path `$AppDir 'Start-DiscoverySession.ps1') @Rest
} elseif (`$Mode -match '^(invoke|local|bare|baremetal)$') {
    & (Join-Path `$AppDir 'Invoke-ServerDiscovery.ps1') @Rest
} elseif (`$Mode -match '^(update|upgrade)$') {
    # Force reinstall from GitHub
    & ([scriptblock]::Create((iwr 'https://raw.githubusercontent.com/matt-magna5/SDT/main/install.ps1' -UseBasicParsing).Content))
} elseif (`$Mode -match '^(version|-v|--version)$') {
    Write-Host 'SDT installed at $AppDir'
    Write-Host 'Version: $Version'
} else {
    & (Join-Path `$AppDir 'Start-DiscoverySessionGUI.ps1') @Rest
}
"@ | Set-Content -Path $ShimPS -Encoding UTF8

# sdt.cmd - CMD-side shim that invokes PowerShell
@"
@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$ShimPS" %*
"@ | Set-Content -Path $ShimCmd -Encoding ASCII

Say "Shims written: sdt.ps1 + sdt.cmd" DarkGreen

# ----- Add BinDir to user PATH if missing ------------------------------------
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $userPath) { $userPath = '' }
$already = ($userPath -split ';') | Where-Object { $_ -ieq $BinDir }
if (-not $already) {
    $newPath = if ($userPath) { "$userPath;$BinDir" } else { $BinDir }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Say "Added to user PATH: $BinDir" DarkGreen
    Say "(Open a NEW terminal to pick up the PATH change.)" DarkYellow
} else {
    Say "PATH already contains $BinDir" DarkGray
}

# ----- Start Menu shortcut ---------------------------------------------------
if (-not $NoShortcut) {
    try {
        $startMenu = [Environment]::GetFolderPath('StartMenu')
        $shortcut  = Join-Path $startMenu 'Programs\Magna5 SDT.lnk'
        New-Item -ItemType Directory -Force -Path (Split-Path $shortcut -Parent) | Out-Null
        $wsh = New-Object -ComObject WScript.Shell
        $s = $wsh.CreateShortcut($shortcut)
        $s.TargetPath = 'powershell.exe'
        $s.Arguments  = "-NoProfile -ExecutionPolicy Bypass -File `"$ShimPS`""
        $s.WorkingDirectory = $AppDir
        $s.IconLocation = 'powershell.exe,0'
        $s.Description = "Launch Magna5 SDT discovery GUI"
        $s.Save()
        Say "Start Menu shortcut: Magna5 SDT" DarkGreen
    } catch {
        Say "Shortcut creation skipped: $($_.Exception.Message)" Yellow
    }
}

Say ""
Say "================================================================" DarkMagenta
Say "  Install complete" Green
Say "================================================================" DarkMagenta
Say ""
Say "Launch options:" Cyan
Say "  sdt           - browser GUI (default)"          DarkGray
Say "  sdt cli       - console Start-DiscoverySession"  DarkGray
Say "  sdt invoke    - local Invoke-ServerDiscovery"    DarkGray
Say "  sdt update    - reinstall from GitHub"           DarkGray
Say "  sdt version   - show install info"               DarkGray
Say ""
Say "Open a NEW terminal and type 'sdt' to start." Yellow
Say ""
